export const jobList = [
    {
      employer: "Employer 1",
      title: "Front End Developer",
      description: "Develop responsive websites with React and CSS.",
      category: "Development",
      location: "Remote",
      budget: { type: "Fixed", amount: 500000 },
      requiredSkills: ["React", "CSS", "HTML"],
      experienceLevel: "Intermediate",
      datePosted: new Date(),
      status: "Open",
    },
    {
      employer: "Employer 2",
      title: "Maid",
      description: "Provide cleaning services for residential or commercial locations.",
      category: "Housekeeping",
      location: "New York, NY",
      budget: { type: "Hourly", amount: 18 },
      requiredSkills: ["Cleaning", "Organizing"],
      experienceLevel: "Apprentice",
      datePosted: new Date(),
      status: "Open",
    },
    {
      employer: "Employer 3",
      title: "Back End Developer",
      description: "Build and maintain server-side logic.",
      category: "Development",
      location: "San Francisco, CA",
      budget: { type: "Fixed", amount: 700000 },
      requiredSkills: ["Node.js", "MongoDB", "API"],
      experienceLevel: "Expert",
      datePosted: new Date(),
      status: "Open",
    },
    {
      employer: "Employer 4",
      title: "Math Tutor",
      description: "Provide online tutoring for high school and college students.",
      category: "Education",
      location: "Remote",
      budget: { type: "Hourly", amount: 50 },
      requiredSkills: ["Math", "Teaching"],
      experienceLevel: "Intermediate",
      datePosted: new Date(),
      status: "Open",
    },
    {
      employer: "Employer 5",
      title: "Social Media Manager",
      description: "Manage and grow social media accounts for brands.",
      category: "Marketing",
      location: "Los Angeles, CA",
      budget: { type: "Fixed", amount: 4000 },
      requiredSkills: ["Social Media", "Marketing", "Content Creation"],
      experienceLevel: "Intermediate",
      datePosted: new Date(),
      status: "Open",
    },
  ];
  